[package]
name = "httpserver"
version = "0.1.0"
edition = "2021"
default-run = "httpserver"

[dependencies]
http-lib = { path = "../http-lib" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
